apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jwks-merge.fullname" . }}-nginx
  labels:
    {{- include "jwks-merge.labels" . | nindent 4 }}
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;

    error_log /var/log/nginx/error.log notice;
    pid       /var/run/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

      access_log /var/log/nginx/access.log  main;

      server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
          return 200 'It Works!';
        }

        location {{ .Values.mergedJwksPath | default "/jwks.json" }} {
          alias /var/local/jwks.json;
        }
      }
    }
