apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jwks-merge
  name: jwks-merge
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: jwks-merge
